Description: >
    HMarn / Udacity Capstone Project
    This template deploys IAM role for EKSCluster and a project cluster.

Parameters:
    ID:
        Description: Unique identifier.
        Type: String

    VpcId:
        Description: Select a VPC that allows instances to access the Internet.
        Type: String
        Default: vpc-0e785190d96840d03

    SGId:
        Description: Select a VPC that allows instances to access the Internet.
        Type: String
        Default: sg-0ef2679a8178606a0

Resources:

    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub cluster-role-${ID}
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - eks.amazonaws.com
                      Action:
                        - sts:AssumeRole
            Path: "/"
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
            Tags:
                - Key: Name
                  Value: !Sub EKSClusterRole-${ID}
                        
    EKSCluster:
        Type: AWS::EKS::Cluster
        Properties:
            Version: "1.24"
            Name: !Sub cluster-${ID}
            RoleArn: !GetAtt EKSClusterRole.Arn
            ResourcesVpcConfig:
                SecurityGroupIds:
                    - !Ref SGId
                SubnetIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                                Fn::Sub: ${ID}-PUB-NETS
            Tags: 
                - Key: Name
                  Value: !Sub EKSCluster-${ID}

Outputs:
    EKSClusterRole:
        Description: Role for accessing and creating EKS Cluster
        Value: !Ref EKSClusterRole
        Export:
            Name: !Sub EKSClusterRole-${ID}

    EKSCluster:
        Description: EKS id
        Value: !Ref EKSCluster
        Export:
            Name: !Sub EKSCluster-${ID}
