Description: >
    HMarn / Udacity Capstone Project
    This template deploys IAM role for EKSCluster and a project cluster.

Parameters:
    ID:
        Description: Unique identifier.
        Type: String

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names.
        Type: String

    VpcId:
        Description: Select a VPC that allows instances to access the Internet.
        Type: String

    SGId:
        Description: Select a VPC that allows instances to access the Internet.
        Type: String

Resources:

    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ${EnvironmentName}-cluster-role
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - eks.amazonaws.com
                      Action:
                        - sts:AssumeRole
            Path: "/"
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-EKSClusterRole-${ID}
                        
    EKSCluster:
        Type: AWS::EKS::Cluster
        Properties:
            Version: "1.24"
            Name: !Sub ${EnvironmentName}-cluster
            RoleArn: !GetAtt EKSClusterRole.Arn
            ResourcesVpcConfig:
                SecurityGroupIds:
                    - !Ref SGId
                SubnetIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                                Fn::Sub: ${EnvironmentName}-PUB-NETS
            Tags: 
                - Key: Name
                  Value: !Sub ${EnvironmentName}-EKSCluster-${ID}

Outputs:
    EKSRoleArn:
        Description: Role for accessing and creating aws resources
        Value: !GetAtt EKSClusterRole.Arn
        Export:
            Name: !Sub ${EnvironmentName}-EKSRole-${ID}

    EKSId:
        Description: EKS id
        Value: !Ref EKSCluster
        Export:
            Name: !Sub ${EnvironmentName}-EKSCluster-${ID}
