apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-app
  labels: 
    app: rolling-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolling-app
  template:
    metadata:
      labels:
        app: rolling-app
        role: rolling-update
    spec:
      containers:
      - name: rolling-deployment-container
        image: haymarnhm/capstone-react-app:v1.0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1